apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- base

namePrefix: dev-

labels:
- pairs:
    environment: dev

replicas:
- name: demo-app
  count: 1
