apiVersion: platform.example.io/v1alpha1
kind: AppFrontend
metadata:
  name: kubecon-countdown
spec:
  containerPort: 8080
  image:
    repository: us-central1-docker.pkg.dev/spaces-playground/demo-platform/kubecon-countdown
    tag: v1.0.1
  replicas: 1
  servicePort: 80
  healthCheck:
    path: /health
    port: 8080
    initialDelaySeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
