apiVersion: platform.example.io/v1alpha1
kind: AppFrontend
metadata:
  name: event-countdown
  namespace: poc
spec:
  image:
    repository: us-central1-docker.pkg.dev/spaces-playground/demo-platform/event-countdown
    tag: v1.0.0
  containerPort: 8080
  servicePort: 80
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  healthCheck:
    path: /healthz
    port: 8080
    initialDelaySeconds: 10
  env:
    - name: PORT
      value: "8080"
    - name: PYTHONUNBUFFERED
      value: "1"
