apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- ../../base

namePrefix: prod-

labels:
- pairs:
    environment: production

replicas:
- name: demo-app
  count: 3
