apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-platform-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/upbound/demo-platform-deployment
    targetRevision: production
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
