name: Validate Manifests

on:
  pull_request:
    branches:
      - main
      - production
    paths:
      - 'base/**'
      - 'kustomization.yaml'
      - '.github/workflows/validate.yaml'

jobs:
  validate:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
      
      - name: Validate manifests
        run: |
          echo "Validating manifests on current branch..."
          kubectl kustomize . > /tmp/manifests.yaml
          kubectl apply --dry-run=client -f /tmp/manifests.yaml
      
      - name: Check for common issues
        run: |
          echo "Checking for common issues..."
          
          # Check for hardcoded secrets
          if grep -r "password:" base/ || grep -r "apiKey:" base/; then
            echo "ERROR: Potential hardcoded secrets found!"
            exit 1
          fi
          
          echo "Basic validation passed!"
      
      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const output = `#### Kubernetes Manifest Validation 🚀
            
            **Validation Results:**
            - ✅ Manifests on this branch are valid
            - ✅ Kustomize build completed successfully
            
            Changes are ready for deployment!`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
